language: common-lisp
sudo: required

env:
  matrix:
    - LISP=sbcl

install:
  - sudo apt-get update
  - sudo apt-get install libsdl1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev
  # Install cl-travis
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash
  # Coveralls support
  - git clone https://github.com/fukamachi/cl-coveralls ~/lisp/cl-coveralls

script:
  - cl -l cl-coveralls
       -e '(ql:quickload :cletris)'
