script: ./build.sh
before_install:
    - sudo apt-get update
    - sudo apt-get install sbcl
    - sudo apt-get install libsdl1.2-dev
    - sudo apt-get install libsdl-image1.2-dev
    - sudo apt-get install libsdl-mixer1.2-dev
